#include "../../include/constants/item.h"
#include "../../include/debug.h"
#include "../../include/pokemon.h"
#include "../../include/save.h"
#include "../../include/script.h"
#include "../../include/types.h"

#ifdef MART_EXPANSION

struct MartItem {
    u16 item_id;
    u16 override_cost;
};

struct BadgeMartItems {
    u16 item_id;
    u8 required_badges;
};

// note: limited to 203 items (~34 pages)
const struct BadgeMartItems sBadgeMart[] = {
    { ITEM_POKE_BALL, 0 },
    { ITEM_GREAT_BALL, 3 },
    { ITEM_ULTRA_BALL, 5 },
    { ITEM_POTION, 0 },
    { ITEM_SUPER_POTION, 1 },
    { ITEM_HYPER_POTION, 5 },
    { ITEM_MAX_POTION, 7 },
    { ITEM_FULL_RESTORE, 8 },
    { ITEM_REVIVE, 3 },
    { ITEM_ANTIDOTE, 0 },
    { ITEM_PARALYZE_HEAL, 0 },
    { ITEM_AWAKENING, 1 },
    { ITEM_BURN_HEAL, 1 },
    { ITEM_ICE_HEAL, 1 },
    { ITEM_FULL_HEAL, 5 },
    { ITEM_ESCAPE_ROPE, 1 },
    { ITEM_REPEL, 1 },
    { ITEM_SUPER_REPEL, 3 },
    { ITEM_MAX_REPEL, 5 },
};

void LONG_CALL InitMartUI(void *taskManager, FieldSystem *fieldSystem, const u16 *items, int kind, int buySell, int decoWhich, const struct MartItem *priceOverrides);

u16 sCherrygroveCityMart[] = {
    ITEM_HEAL_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY, 0xFFFF
};

u16 sVioletCityMart[] = {
    ITEM_HEAL_BALL, ITEM_NET_BALL, ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY,
    ITEM_TM113, ITEM_TM116, ITEM_TM175, ITEM_TM182, ITEM_TM193, 0xFFFF
};

u16 sAzaleaCityMart[] = {
    ITEM_HEAL_BALL, ITEM_NET_BALL, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 
    ITEM_TM105, ITEM_TM117, ITEM_TM119, ITEM_TM130, ITEM_GALARICA_WREATH, ITEM_GALARICA_CUFF, 0xFFFF
};

u16 sGoldenrodDepartmentUpper2F[] = {
    ITEM_POTION, ITEM_SUPER_POTION, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_REVIVE,
    ITEM_ANTIDOTE, ITEM_PARALYZE_HEAL, ITEM_BURN_HEAL, ITEM_ICE_HEAL, ITEM_AWAKENING,
    ITEM_FULL_HEAL, ITEM_ESCAPE_ROPE, ITEM_POKE_DOLL,
    ITEM_REPEL, ITEM_SUPER_REPEL, ITEM_MAX_REPEL, ITEM_HEART_SCALE, 0xFFFF
};

u16 sGoldenrodDepartmentLower2F[] = {
    ITEM_POKE_BALL, ITEM_GREAT_BALL, ITEM_ULTRA_BALL, ITEM_NET_BALL, ITEM_DIVE_BALL,
    ITEM_NEST_BALL, ITEM_REPEAT_BALL, ITEM_TIMER_BALL, ITEM_DUSK_BALL, ITEM_HEAL_BALL,
    ITEM_QUICK_BALL, ITEM_CHERISH_BALL, ITEM_FAST_BALL, ITEM_LEVEL_BALL, ITEM_LURE_BALL,
    ITEM_HEAVY_BALL, ITEM_LOVE_BALL, ITEM_FRIEND_BALL, ITEM_MOON_BALL, ITEM_SPORT_BALL,
    ITEM_DREAM_BALL, ITEM_BEAST_BALL, 0xFFFF
};

u16 sGoldenrodDepartment3F[] = {
    ITEM_X_SPEED, ITEM_X_ATTACK, ITEM_X_DEFENSE, ITEM_GUARD_SPEC, ITEM_DIRE_HIT,
    ITEM_X_ACCURACY, ITEM_X_SP_ATK, ITEM_X_SP_DEF, ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS,
    ITEM_HP_UP, ITEM_LONELY_MINT, ITEM_ADAMANT_MINT, ITEM_NAUGHTY_MINT, ITEM_BRAVE_MINT, ITEM_BOLD_MINT,
    ITEM_IMPISH_MINT, ITEM_LAX_MINT, ITEM_RELAXED_MINT, ITEM_MODEST_MINT, ITEM_MILD_MINT, ITEM_RASH_MINT,
    ITEM_QUIET_MINT, ITEM_CALM_MINT, ITEM_GENTLE_MINT, ITEM_CAREFUL_MINT, ITEM_SASSY_MINT, ITEM_TIMID_MINT,
    ITEM_HASTY_MINT, ITEM_JOLLY_MINT, ITEM_NAIVE_MINT, ITEM_SERIOUS_MINT, ITEM_ABILITY_URGE, ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH, ITEM_ABILITY_SHIELD, ITEM_CLEFABLITE, ITEM_VICTREEBELITE, ITEM_STARMINITE,
    ITEM_DRAGONINITE, ITEM_MEGANIUMITE, ITEM_FERALIGITE, ITEM_SKARMORITE, ITEM_FROSLASSITE, ITEM_HEATRANITE,
    ITEM_DARKRANITE, ITEM_EMBOARITE, ITEM_EXCADRITE, ITEM_SCOLIPITE, ITEM_SCRAFTINITE, ITEM_EELEKTROSSITE, ITEM_CHANDELURITE,
    ITEM_CHESNAUGHTITE, ITEM_DELPHOXITE, ITEM_GRENINJITE, ITEM_PYROARITE, ITEM_FLOETTITE, ITEM_MALAMARITE, ITEM_BARBARACITE,
    ITEM_DRAGALGITE, ITEM_HAWLUCHANITE, ITEM_ZYGARDITE, ITEM_DRAMPANITE, ITEM_ZERAORITE, ITEM_FALINKSITE,
    ITEM_RAICHUNITE_X, ITEM_RAICHUNITE_Y, ITEM_CHIMECHITE, ITEM_ABSOLITE_Z, ITEM_STARAPTITE, ITEM_GARCHOMPITE_Z, 
    ITEM_LUCARIONITE_Z, ITEM_GOLURKITE, ITEM_MEOWSTICITE, ITEM_CRABOMINITE, ITEM_GOLISOPITE, ITEM_MAGEARNITE, 
    ITEM_SCOVILLAINITE, ITEM_BAXCALIBRITE, ITEM_TATSUGIRINITE, ITEM_GLIMMORANITE, 0xFFFF
};

u16 sGoldenrodDepartment4F[] = {
    ITEM_TART_APPLE, ITEM_SWEET_APPLE, ITEM_SYRUPY_APPLE, ITEM_CRACKED_POT, ITEM_METAL_ALLOY, 
    ITEM_MALICIOUS_ARMOR, ITEM_AUSPICIOUS_ARMOR, ITEM_LINKING_CORD, ITEM_BLACK_AUGURITE, ITEM_SUN_STONE,
    ITEM_MOON_STONE, ITEM_FIRE_STONE, ITEM_THUNDER_STONE, ITEM_WATER_STONE, ITEM_LEAF_STONE, ITEM_SHINY_STONE,
    ITEM_DUSK_STONE, ITEM_DAWN_STONE, ITEM_ICE_STONE, ITEM_PROTECTOR, ITEM_ELECTIRIZER, ITEM_MAGMARIZER, ITEM_DUBIOUS_DISC,
    ITEM_REAPER_CLOTH, ITEM_RAZOR_CLAW, ITEM_RAZOR_FANG, ITEM_METAL_COAT, ITEM_PRISM_SCALE, ITEM_DEEP_SEA_TOOTH, ITEM_DEEP_SEA_SCALE, ITEM_DRAGON_SCALE, ITEM_UP_GRADE, ITEM_KINGS_ROCK,
    ITEM_GENGARITE, ITEM_GARDEVOIRITE, ITEM_AMPHAROSITE, ITEM_VENUSAURITE, ITEM_CHARIZARDITE_X,
    ITEM_BLASTOISINITE, ITEM_CHARIZARDITE_Y, ITEM_MEWTWONITE_X, ITEM_MEWTWONITE_Y, ITEM_BLAZIKENITE, ITEM_MEDICHAMITE, ITEM_HOUNDOOMINITE, ITEM_AGGRONITE,
    ITEM_BANETTITE, ITEM_TYRANITARITE, ITEM_SCIZORITE, ITEM_PINSIRITE, ITEM_AERODACTYLITE, ITEM_LUCARIONITE,
    ITEM_ABOMASITE, ITEM_KANGASKHANITE, ITEM_GYARADOSITE, ITEM_ABSOLITE, ITEM_ALAKAZITE, ITEM_HERACRONITE,
    ITEM_MAWILITE, ITEM_MANECTITE, ITEM_GARCHOMPITE, ITEM_LATIASITE, ITEM_LATIOSITE, ITEM_SWAMPERTITE,
    ITEM_SCEPTILITE, ITEM_SABLENITE, ITEM_ALTARIANITE, ITEM_GALLADITE, ITEM_AUDINITE, ITEM_METAGROSSITE,
    ITEM_SHARPEDONITE, ITEM_SLOWBRONITE, ITEM_STEELIXITE, ITEM_PIDGEOTITE, ITEM_GLALITITE, ITEM_DIANCITE, ITEM_CAMERUPTITE,
    ITEM_LOPUNNITE, ITEM_SALAMENCITE, ITEM_BEEDRILLITE, ITEM_MEGA_RING, 0xFFFF
};

u16 sGoldenrodDepartment5F[] = {
    ITEM_TM070, ITEM_TM017, ITEM_TM054, ITEM_TM083, ITEM_TM016,
    ITEM_TM033, ITEM_TM022, ITEM_TM052, ITEM_TM038, ITEM_TM025,
    ITEM_TM014, ITEM_TM015, ITEM_TM094, ITEM_TM100_SV, ITEM_TM103,
    ITEM_TM107, ITEM_TM112, ITEM_TM116, ITEM_TM120, ITEM_TM129, ITEM_TM132,
    ITEM_TM140, ITEM_TM150, ITEM_TM157, ITEM_TM160, ITEM_TM226, ITEM_TR00, ITEM_TR19,
    ITEM_TR24, ITEM_TR36, ITEM_TR50, ITEM_TR65, ITEM_TR71, ITEM_TR84, ITEM_TR86,
    ITEM_TR90, ITEM_TR98, 0xFFFF
};

u16 sGoldenrodHerbs[] = {
    ITEM_HEAL_POWDER, ITEM_ENERGY_POWDER, ITEM_ENERGY_ROOT, ITEM_REVIVAL_HERB, ITEM_WHITE_HERB, ITEM_MENTAL_HERB,
    ITEM_POWER_HERB, ITEM_MIRROR_HERB,  0xFFFF
};

u16 sEcruteakMart[] = {
    ITEM_HEAL_BALL, ITEM_NET_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY,
    ITEM_TM151, ITEM_TM181, ITEM_TM198, ITEM_TM221, ITEM_TM224,  0xFFFF
};

u16 sOlivineMart[] = {
    ITEM_HEAL_BALL, ITEM_NET_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY,
    ITEM_TM144, ITEM_TM145, ITEM_TM146, ITEM_TM196, ITEM_TM200, ITEM_TR07, ITEM_TR14, ITEM_TR18, 0xFFFF
};

u16 sCianwoodPharmacy[] = {
    ITEM_POTION, ITEM_SUPER_POTION, ITEM_HYPER_POTION, ITEM_FULL_HEAL, ITEM_REVIVE, ITEM_SCROLL_OF_DARKNESS, ITEM_SCROLL_OF_WATERS,
    ITEM_TR20, ITEM_TR23, ITEM_TR34, ITEM_TR41, ITEM_TR45, ITEM_PEAT_BLOCK,  0xFFFF
};

u16 sBlackthornAndBattleFrontierMart[] = {
    ITEM_NET_BALL, ITEM_DUSK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 
    ITEM_TM153, ITEM_TM154, ITEM_TM155, ITEM_TR54, ITEM_TR55, ITEM_TR67, ITEM_TR80, ITEM_TR93, ITEM_TR94, 0xFFFF
};

u16 sIndigoPlateau[] = {
    ITEM_ULTRA_BALL, ITEM_MAX_REPEL, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_FULL_RESTORE, ITEM_REVIVE, ITEM_FULL_HEAL, 0xFFFF
};

u16 sVermilionAndSafariMart[] = {
    ITEM_NEST_BALL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sSaffronMart[] = {
    ITEM_DUSK_BALL, ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sLavenderMart[] = {
    ITEM_DUSK_BALL, ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sCeruleanMart[] = {
    ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sCeladonDepartmentUpper2F[] = {
    ITEM_POTION, ITEM_SUPER_POTION, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_REVIVE,
    ITEM_ANTIDOTE, ITEM_PARALYZE_HEAL, ITEM_BURN_HEAL, ITEM_ICE_HEAL, ITEM_AWAKENING,
    ITEM_FULL_HEAL, ITEM_ESCAPE_ROPE, ITEM_POKE_DOLL,
    ITEM_REPEL, ITEM_SUPER_REPEL, ITEM_MAX_REPEL, 0xFFFF
};

u16 sCeladonDepartmentLower2F[] = {
    ITEM_POKE_BALL, ITEM_GREAT_BALL, ITEM_ULTRA_BALL, ITEM_NET_BALL, ITEM_DIVE_BALL,
    ITEM_NEST_BALL, ITEM_REPEAT_BALL, ITEM_TIMER_BALL, ITEM_DUSK_BALL, ITEM_HEAL_BALL,
    ITEM_QUICK_BALL, ITEM_CHERISH_BALL, ITEM_FAST_BALL, ITEM_LEVEL_BALL, ITEM_LURE_BALL,
    ITEM_HEAVY_BALL, ITEM_LOVE_BALL, ITEM_FRIEND_BALL, ITEM_MOON_BALL, ITEM_SPORT_BALL,
    ITEM_DREAM_BALL, ITEM_BEAST_BALL, 0xFFFF
};

u16 sCeladonDepartment3F[] = {
    ITEM_TM021, ITEM_TM027, ITEM_TM087, ITEM_TM078, ITEM_TM012, ITEM_TM041, ITEM_TM020, ITEM_TM028, ITEM_TM076, ITEM_TM055, ITEM_TM072, ITEM_TM079, 0xFFFF
};

u16 sCeladonDepartment4F[] = {
    ITEM_GENGARITE, ITEM_GARDEVOIRITE, ITEM_AMPHAROSITE, ITEM_VENUSAURITE, ITEM_CHARIZARDITE_X,
    ITEM_BLASTOISINITE, ITEM_CHARIZARDITE_Y, ITEM_MEWTWONITE_X, ITEM_MEWTWONITE_Y, ITEM_BLAZIKENITE, ITEM_MEDICHAMITE, ITEM_HOUNDOOMINITE, ITEM_AGGRONITE,
    ITEM_BANETTITE, ITEM_TYRANITARITE, ITEM_SCIZORITE, ITEM_PINSIRITE, ITEM_AERODACTYLITE, ITEM_LUCARIONITE,
    ITEM_ABOMASITE, ITEM_KANGASKHANITE, ITEM_GYARADOSITE, ITEM_ABSOLITE, ITEM_ALAKAZITE, ITEM_HERACRONITE,
    ITEM_MAWILITE, ITEM_MANECTITE, ITEM_GARCHOMPITE, ITEM_LATIASITE, ITEM_LATIOSITE, ITEM_SWAMPERTITE,
    ITEM_SCEPTILITE, ITEM_SABLENITE, ITEM_ALTARIANITE, ITEM_GALLADITE, ITEM_AUDINITE, ITEM_METAGROSSITE,
    ITEM_SHARPEDONITE, ITEM_SLOWBRONITE, ITEM_STEELIXITE, ITEM_PIDGEOTITE, ITEM_GLALITITE, ITEM_DIANCITE, ITEM_CAMERUPTITE,
    ITEM_LOPUNNITE, ITEM_SALAMENCITE, ITEM_BEEDRILLITE, 0xFFFF
};

u16 sCeladonDepartmentLeft5F[] = {
    ITEM_ROOT_FOSSIL, ITEM_CLAW_FOSSIL, ITEM_HELIX_FOSSIL, ITEM_DOME_FOSSIL, ITEM_OLD_AMBER,
    ITEM_ARMOR_FOSSIL, ITEM_SKULL_FOSSIL, ITEM_COVER_FOSSIL, ITEM_PLUME_FOSSIL, ITEM_JAW_FOSSIL, ITEM_SAIL_FOSSIL, 0xFFFF
};

u16 sCeladonDepartmentRight5F[] = {
    ITEM_X_SPEED, ITEM_X_ATTACK, ITEM_X_DEFENSE, ITEM_GUARD_SPEC, ITEM_DIRE_HIT,
    ITEM_X_ACCURACY, ITEM_X_SP_ATK, ITEM_X_SP_DEF, ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS,
    ITEM_HP_UP, ITEM_LONELY_MINT, ITEM_ADAMANT_MINT, ITEM_NAUGHTY_MINT, ITEM_BRAVE_MINT, ITEM_BOLD_MINT,
    ITEM_IMPISH_MINT, ITEM_LAX_MINT, ITEM_RELAXED_MINT, ITEM_MODEST_MINT, ITEM_MILD_MINT, ITEM_RASH_MINT,
    ITEM_QUIET_MINT, ITEM_CALM_MINT, ITEM_GENTLE_MINT, ITEM_CAREFUL_MINT, ITEM_SASSY_MINT, ITEM_TIMID_MINT,
    ITEM_HASTY_MINT, ITEM_JOLLY_MINT, ITEM_NAIVE_MINT, ITEM_SERIOUS_MINT, ITEM_ABILITY_URGE, ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH, ITEM_ABILITY_SHIELD, 0xFFFF
};

u16 sFuschiaMart[] = {
    ITEM_DUSK_BALL, ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sPewterMart[] = {
    ITEM_NEST_BALL, ITEM_QUICK_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sViridianMart[] = {
    ITEM_NET_BALL, ITEM_HEAL_BALL, ITEM_ORAN_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY,
    ITEM_CHERI_BERRY, ITEM_LEPPA_BERRY, ITEM_ASPEAR_BERRY, ITEM_RAWST_BERRY, ITEM_PERSIM_BERRY, ITEM_SITRUS_BERRY, ITEM_LUM_BERRY, 0xFFFF
};

u16 sMtMoonSquare[] = {
    ITEM_POKE_DOLL, ITEM_FRESH_WATER, ITEM_SODA_POP, ITEM_LEMONADE, ITEM_REPEL, ITEM_HEART_MAIL, 0xFFFF
};

u16 sMahoganyPreRocketHideout[] = {
    ITEM_TINY_MUSHROOM, ITEM_POKE_BALL, ITEM_POTION, 0xFFFF
};

u16 sMahoganyPostRocketHideout[] = {
    ITEM_LEFTOVERS, ITEM_CHOICE_BAND, ITEM_CHOICE_SCARF, ITEM_CHOICE_SPECS, ITEM_ZOOM_LENS,
    ITEM_WIDE_LENS, ITEM_SCOPE_LENS, ITEM_AIR_BALLOON, ITEM_ASSAULT_VEST, ITEM_EXPERT_BELT, ITEM_BRIGHT_POWDER,
    ITEM_EJECT_BUTTON, ITEM_EJECT_PACK, ITEM_EVIOLITE, ITEM_FLAME_ORB, ITEM_FOCUS_BAND, ITEM_FOCUS_SASH,
    ITEM_ICY_ROCK, ITEM_SMOOTH_ROCK, ITEM_HEAT_ROCK, ITEM_DAMP_ROCK, ITEM_LIFE_ORB, ITEM_LIGHT_CLAY, ITEM_LOADED_DICE,
    ITEM_POWER_HERB, ITEM_QUICK_CLAW, ITEM_ROCKY_HELMET, ITEM_TOXIC_ORB, ITEM_WEAKNESS_POLICY, ITEM_WHITE_HERB,
    ITEM_FIRE_GEM, ITEM_WATER_GEM, ITEM_ELECTRIC_GEM, ITEM_GRASS_GEM, ITEM_ICE_GEM, ITEM_FIGHTING_GEM, ITEM_POISON_GEM,
    ITEM_GROUND_GEM, ITEM_FLYING_GEM, ITEM_PSYCHIC_GEM, ITEM_BUG_GEM, ITEM_ROCK_GEM, ITEM_GHOST_GEM,
    ITEM_DRAGON_GEM, ITEM_DARK_GEM, ITEM_STEEL_GEM, ITEM_NORMAL_GEM, ITEM_FAIRY_GEM, 0xFFFF
};

BOOL ScrCmd_MartBuy(SCRIPTCONTEXT *ctx)
{
    u16 unused UNUSED = ScriptGetVar(ctx);

    u16 items[NELEMS(sBadgeMart) + 1];
    u8 badgeCount = 0;
    u8 index = 0;
    u32 i;

    for (i = 0; i < 16; i++) {
        if (PlayerProfile_TestBadgeFlag(Sav2_PlayerData_GetProfileAddr(ctx->fsys->savedata), i) == TRUE) {
            badgeCount++;
        }
    }

    for (i = 0; i < NELEMS(sBadgeMart); i++) {
        if (badgeCount >= sBadgeMart[i].required_badges) {
            items[index] = sBadgeMart[i].item_id;
            index++;
        }
    }

    items[index] = 0xFFFF;
    InitMartUI(ctx->taskman, ctx->fsys, items, 0, 0, 0, 0); // this doesn't honor price overrides
    return TRUE;
}

#endif // MART_EXPANSION

#ifdef POKEATHLON_SHOP_EXPANSION

const struct MartItem sPokeathlonShop_Sunday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_KINGS_ROCK, 3000 },
    { ITEM_HEART_SCALE, 1000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Monday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_MOON_STONE, 3000 },
    { ITEM_RARE_CANDY, 2000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Tuesday[] = {
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_FIRE_STONE, 2500 },
    { ITEM_PP_UP, 1000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Wednesday[] = {
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_WATER_STONE, 2500 },
    { ITEM_HEART_SCALE, 1000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Thursday[] = {
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_THUNDER_STONE, 2500 },
    { ITEM_PP_UP, 1000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Friday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_METAL_COAT, 2500 },
    { ITEM_NUGGET, 500 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_Saturday[] = {
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_LEAF_STONE, 2500 },
    { ITEM_RARE_CANDY, 2000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexSunday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_KINGS_ROCK, 3000 },
    { ITEM_HEART_SCALE, 1000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_NUGGET, 500 },
    { ITEM_SUN_STONE, 3000 },
    { ITEM_FIRE_STONE, 2500 },
    { ITEM_SHINY_STONE, 3000 },
    { ITEM_DAWN_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexMonday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_MOON_STONE, 3000 },
    { ITEM_RARE_CANDY, 2000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_KINGS_ROCK, 3000 },
    { ITEM_SUN_STONE, 3000 },
    { ITEM_WATER_STONE, 2500 },
    { ITEM_SHINY_STONE, 3000 },
    { ITEM_DUSK_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexTuesday[] = {
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_FIRE_STONE, 2500 },
    { ITEM_PP_UP, 1000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_METAL_COAT, 2500 },
    { ITEM_WATER_STONE, 2500 },
    { ITEM_LEAF_STONE, 2500 },
    { ITEM_DUSK_STONE, 3000 },
    { ITEM_DAWN_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexWednesday[] = {
    { ITEM_BLUE_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_WATER_STONE, 2500 },
    { ITEM_HEART_SCALE, 1000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_DRAGON_SCALE, 2500 },
    { ITEM_THUNDER_STONE, 2500 },
    { ITEM_MOON_STONE, 3000 },
    { ITEM_SHINY_STONE, 3000 },
    { ITEM_DAWN_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexThursday[] = {
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_PINK_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_THUNDER_STONE, 2500 },
    { ITEM_PP_UP, 1000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_KINGS_ROCK, 3000 },
    { ITEM_FIRE_STONE, 2500 },
    { ITEM_LEAF_STONE, 2500 },
    { ITEM_SHINY_STONE, 3000 },
    { ITEM_DUSK_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexFriday[] = {
    { ITEM_RED_APRICORN, 200 },
    { ITEM_YELLOW_APRICORN, 200 },
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_METAL_COAT, 2500 },
    { ITEM_NUGGET, 500 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_DRAGON_SCALE, 2500 },
    { ITEM_WATER_STONE, 2500 },
    { ITEM_SUN_STONE, 3000 },
    { ITEM_DUSK_STONE, 3000 },
    { ITEM_DAWN_STONE, 3000 },
    { 0xFFFF, 0 },
};

const struct MartItem sPokeathlonShop_NatdexSaturday[] = {
    { ITEM_GREEN_APRICORN, 200 },
    { ITEM_WHITE_APRICORN, 200 },
    { ITEM_BLACK_APRICORN, 200 },
    { ITEM_MOOMOO_MILK, 100 },
    { ITEM_LEAF_STONE, 2500 },
    { ITEM_RARE_CANDY, 2000 },
    { ITEM_FULL_RESTORE, 500 },
    { ITEM_METAL_COAT, 2500 },
    { ITEM_THUNDER_STONE, 2500 },
    { ITEM_SHINY_STONE, 3000 },
    { ITEM_DUSK_STONE, 3000 },
    { ITEM_DAWN_STONE, 3000 },
    { 0xFFFF, 0 },
};

#endif // POKEATHLON_SHOP_EXPANSION
